# Generated by Django 3.1.4 on 2020-12-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_course',
            field=models.ImageField(default=None, upload_to='static/media/blog'),
        ),
    ]
