# Generated by Django 3.1.4 on 2020-12-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='CustomerUser',
        ),
        migrations.DeleteModel(
            name='CustomerUser',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
