# Generated by Django 3.1.4 on 2020-12-15 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customeruser_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='image_user',
        ),
    ]
