# Generated by Django 3.1.4 on 2020-12-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='title',
        ),
    ]
