# Generated by Django 3.1.4 on 2020-12-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='price',
        ),
        migrations.AlterField(
            model_name='variation',
            name='sale_price',
            field=models.FloatField(default=0),
        ),
    ]
